In [1]:
import json
from urllib.request import urlopen
import pandas as pd

Open sensor_data.json file

In [2]:
with open('JSONFILES/sensor_data.json') as f:
  data = json.load(f)
  sensor_data=data['array']
  sensor_data_df = pd.DataFrame(sensor_data)

In [3]:
sensor_data_df

      temperature   humidity   roomArea    id      timestamp
0       21.279782  87.252551  roomArea1     1  1593666000000
1       21.850242  89.434610  roomArea2     2  1593666000000
2       25.933317  90.486834  roomArea3     3  1593666000000
3       21.738958  95.380901  roomArea1     4  1593667800053
4       26.092710  92.225805  roomArea2     5  1593667800053
...           ...        ...        ...   ...            ...
1435    19.627947  90.115336  roomArea2  1436  1594526424353
1436    23.906994  92.561583  roomArea3  1437  1594526424353
1437    22.617990  93.168535  roomArea1  1438  1594528224401
1438    22.810529  89.656614  roomArea2  1439  1594528224401
1439    18.366510  95.243434  roomArea3  1440  1594528224401

[1440 rows x 5 columns]

In [4]:
sensor_data_df['day'] = pd.to_datetime(sensor_data_df['timestamp'], unit='ms').dt.date

In [5]:
sensor_data_df

      temperature   humidity   roomArea    id      timestamp         day
0       21.279782  87.252551  roomArea1     1  1593666000000  2020-07-02
1       21.850242  89.434610  roomArea2     2  1593666000000  2020-07-02
2       25.933317  90.486834  roomArea3     3  1593666000000  2020-07-02
3       21.738958  95.380901  roomArea1     4  1593667800053  2020-07-02
4       26.092710  92.225805  roomArea2     5  1593667800053  2020-07-02
...           ...        ...        ...   ...            ...         ...
1435    19.627947  90.115336  roomArea2  1436  1594526424353  2020-07-12
1436    23.906994  92.561583  roomArea3  1437  1594526424353  2020-07-12
1437    22.617990  93.168535  roomArea1  1438  1594528224401  2020-07-12
1438    22.810529  89.656614  roomArea2  1439  1594528224401  2020-07-12
1439    18.366510  95.243434  roomArea3  1440  1594528224401  2020-07-12

[1440 rows x 6 columns]

### Aggregate sensor data from JSON file on roomArea and by day.
### min, max, median, and avg from sensors value (temperature, humidity)
e.g. room area 1 in july 2, 2020 has {min, max, median, average} {temp, humidity} of some values

In [6]:
result = sensor_data_df.groupby(['roomArea', 'day']).agg({'temperature': ['mean', 'min', 'max','median'],'humidity': ['mean', 'min', 'max','median'] })

In [7]:
result

                     temperature                                    humidity  \
                            mean        min        max     median       mean
roomArea  day
roomArea1 2020-07-02   20.975726  17.174949  26.673704  20.853460  92.255201
          2020-07-03   21.688645  17.005340  26.769534  21.437577  91.799654
          2020-07-04   21.827394  17.060048  26.907201  21.626358  91.289157
          2020-07-05   22.054218  17.051165  26.893966  21.743976  91.752173
          2020-07-06   22.134418  17.115379  26.693667  22.195780  92.362963
          2020-07-07   21.326926  17.218585  26.966150  20.875176  92.203028
          2020-07-08   21.894950  17.434826  26.912232  21.476574  92.367943
          2020-07-09   22.447341  17.328260  26.980360  23.619499  92.384085
          2020-07-10   21.527358  17.116608  26.943562  21.012436  92.393586
          2020-07-11   22.282162  17.131516  26.812108  22.091964  91.940861
          2020-07-12   22.995579  17.354796  26.777606  23.682022  91.980610
roomArea2 2020-07-02   21.693697  17.257017  26.729741  21.284362  91.970106
          2020-07-03   21.446452  17.108971  26.378676  21.193057  92.683502
          2020-07-04   21.961981  17.133661  26.614564  21.230175  91.779957
          2020-07-05   21.548422  17.271888  26.652219  21.499209  91.985922
          2020-07-06   22.902401  17.128593  26.824174  23.088382  91.541010
          2020-07-07   21.936241  17.212446  26.759767  22.248660  92.058505
          2020-07-08   22.068224  17.085249  26.792468  22.566805  92.075879
          2020-07-09   22.510251  17.055808  26.999287  22.608411  91.790202
          2020-07-10   21.802895  17.033950  26.948742  22.093384  91.895116
          2020-07-11   22.847854  17.417361  26.941793  22.826801  92.352712
          2020-07-12   20.632794  17.515441  25.764404  19.719849  90.561231
roomArea3 2020-07-02   21.981684  17.126253  25.933317  22.196923  92.220290
          2020-07-03   21.599302  17.209985  26.786283  21.522606  91.268427
          2020-07-04   21.898403  17.219402  26.842787  22.020249  92.076432
          2020-07-05   21.718636  17.141040  26.979058  21.292097  91.603356
          2020-07-06   21.676544  17.392665  26.950621  21.175535  92.378088
          2020-07-07   21.968644  17.439981  26.854977  21.705379  92.556034
          2020-07-08   22.206934  17.069630  26.685504  22.966985  92.137274
          2020-07-09   22.126801  17.904846  26.953812  22.678729  92.452956
          2020-07-10   21.708990  17.841353  26.860020  21.384723  91.211573
          2020-07-11   22.590635  17.411602  26.804511  22.914620  91.438487
          2020-07-12   21.177825  17.546673  26.981793  21.716050  92.644962


                            min        max     median
roomArea  day
roomArea1 2020-07-02  87.113511  96.764061  92.071502
          2020-07-03  87.486024  96.736813  92.173740
          2020-07-04  87.175241  96.919821  90.959930
          2020-07-05  87.380310  96.909704  91.862173
          2020-07-06  87.384378  96.999543  92.446474
          2020-07-07  87.233410  96.859104  92.455295
          2020-07-08  87.338590  96.542438  92.588461
          2020-07-09  87.363798  96.755762  92.472846
          2020-07-10  87.128247  96.941817  92.940806
          2020-07-11  87.133256  96.796783  91.889241
          2020-07-12  87.032932  95.953356  91.964332
roomArea2 2020-07-02  87.425267  96.949686  91.888630
          2020-07-03  87.007960  96.736152  93.104771
          2020-07-04  87.039648  96.609589  91.975620
          2020-07-05  87.223854  96.579730  92.044745
          2020-07-06  87.153071  96.946636  90.881709
          2020-07-07  87.298954  96.787666  91.911759
          2020-07-08  87.242140  96.692819  91.797144
          2020-07-09  87.042187  96.754355  91.564216
          2020-07-10  87.032323  96.937016  91.786858
          2020-07-11  87.095928  96.478993  92.411163
          2020-07-12  87.902797  96.696650  89.812629
roomArea3 2020-07-02  87.253083  96.796979  91.997936
          2020-07-03  87.105349  96.920165  91.059564
          2020-07-04  87.569960  96.885803  91.896271
          2020-07-05  87.266470  96.707755  91.147800
          2020-07-06  87.108905  96.921077  92.990329
          2020-07-07  87.026001  96.718349  93.256938
          2020-07-08  87.192079  96.986598  92.388111
          2020-07-09  87.683816  96.760668  92.904631
          2020-07-10  87.075597  96.716429  90.818581
          2020-07-11  87.086575  96.909171  91.032005
          2020-07-12  87.385461  96.506475  93.902509

In [8]:
result.to_json('JSONFiles/sensor_data_modified.json', orient='index', indent=2)